### ISSUE TITLE
Publish version with pakage.json types fix.

### ISSUE THREAD

**Issue by adamdama** [abdala/fetch-aws4#2]
A few months back a PR to fix the types field in the package.json was merged
https://github.com/abdala/fetch-aws4/pull/1

Is it possible to get the version number updated and published to NPM? When we install v1.0.1 we still get the warnings about the incorrect field name.

**Comment by abdala** [comment]
Hey @adamdama. Thank you for you report.

I just released version 2 now.

Hope everything works fine for you now.

Cheers
